version: "3.8"

services:
  db:
    image: postgres:15
    container_name: remitly-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: remitly_user
      POSTGRES_PASSWORD: remitly_pass
      POSTGRES_DB: remitly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
