version: "3"
services:
  remitly-db:
    image: postgres:15
    container_name: remitly-db
    environment:
      POSTGRES_USER: Maqa
      POSTGRES_PASSWORD: password_2025
      POSTGRES_DB: remitly_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  remitly-api:
    build: .
    container_name: remitly-api
    ports:
      - "8080:8080"
    depends_on:
      - remitly-db
    env_file:
      - .env

volumes:
  pgdata:
